name: ephemeral-runners
on: workflow_dispatch
jobs:
    manage-runners:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: cellinacywinska/runners-github-action-attempt@develop
            with:
              pulumi-config-path: '../../config.yaml'
              pulumi-goal: 'create'
              pulumi-stack-name: 'dev1'
              pulumi-cloud-provider: 'aws'
              pulumi-config-passphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
              cloud-architecture: 'arm64'
              github-app-id: ${{ secrets.APP_ID }}
              github-app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}
              pulumi-access-token: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          

